spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wisdom_rental}
    username: ${SPRING_DATASOURCE_USERNAME:wisdom}
    password: ${SPRING_DATASOURCE_PASSWORD:wisdom}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
server:
  port: 8080
